In [49]:
import numpy as np

STUDENT_NAME = "Brylle Edsil F. Untalasco"
STUDENT_ID = 384

np.random.seed(STUDENT_ID)

data = np.random.randint(1, STUDENT_ID % 100 + 50, size=10)

print(f"{STUDENT_NAME}'s Array:", data)

mean_val = np.mean(data)
std_val = np.std(data)

print("Mean:", mean_val, "Std Dev:", std_val)

Brylle Edsil F. Untalasco's Array: [94 13  5 60 82 48 41 17 56 87]
Mean: 50.3 Std Dev: 30.053452380716593


In [50]:
import numpy as np

STUDENT_NAME = "Brylle Edsil F. Untalasco"
STUDENT_ID = 384

np.random.seed(STUDENT_ID)

matrix = np.random.randint(1, STUDENT_ID % 50 + 20, size=(3,4))

print(f"{STUDENT_NAME}'s Matrix:\n", matrix)

row_sums = np.sum(matrix, axis=1)
col_sums = np.sum(matrix, axis=0)

print("Row sums:", row_sums)
print("Column sums:", col_sums)

Brylle Edsil F. Untalasco's Matrix:
 [[39 30 36 13]
 [26  5 23 36]
 [50 19 22 18]]
Row sums: [118  90 109]
Column sums: [115  54  81  67]


In [51]:
import numpy as np

STUDENT_NAME = "Brylle Edsil F. Untalasco"
STUDENT_ID = 384

np.random.seed(STUDENT_ID)

arr3d = np.random.randint(0, STUDENT_ID % 20 + 10, size=(3,3,3))

print(f"{STUDENT_NAME}'s 3D Array:\n", arr3d)

slice_mid = arr3d[:,1,:]
print("Slice[:,1,:]:\n", slice_mid)

Brylle Edsil F. Untalasco's 3D Array:
 [[[ 6 13  3]
  [12  9  4]
  [ 6  3 11]]

 [[ 1  2  5]
  [ 1  7  8]
  [ 0  7  6]]

 [[ 0 13  5]
  [11 11 12]
  [ 4 10  6]]]
Slice[:,1,:]:
 [[12  9  4]
 [ 1  7  8]
 [11 11 12]]


In [52]:
import numpy as np

STUDENT_NAME = "Brylle Edsil F. Untalasco"
STUDENT_ID = 384

np.random.seed(STUDENT_ID)

x = np.random.randint(1, STUDENT_ID % 100 + 50, size=10)

filtered = x[(x > STUDENT_ID % 50) & (x < STUDENT_ID % 100)]

print(f"{STUDENT_NAME}'s Original:", x)
print("Filtered subset:", filtered)

Brylle Edsil F. Untalasco's Original: [94 13  5 60 82 48 41 17 56 87]
Filtered subset: [60 82 48 41 56]


In [53]:
import numpy as np

STUDENT_NAME = "Brylle Edsil F. Untalasco"
STUDENT_ID = 384

np.random.seed(STUDENT_ID)

A = np.random.randint(1, STUDENT_ID % 50 + 20, size=(2,2))
B = np.random.randint(1, STUDENT_ID % 50 + 20, size=(2,2))

print("Matrix A:\n", A)
print("Matrix B:\n", B)

product = A @ B
det_A = np.linalg.det(A)

print("A @ B:\n", product)
print("Determinant of A:", det_A)

Matrix A:
 [[39 30]
 [36 13]]
Matrix B:
 [[26  5]
 [23 36]]
A @ B:
 [[1704 1275]
 [1235  648]]
Determinant of A: -572.9999999999997


In [54]:
import numpy as np

STUDENT_NAME = "Brylle Edsil F. Untalasco"
STUDENT_ID = 384

angles = np.linspace(0, 2*np.pi, 8)

sine_vals = np.sin(angles)
cos_vals = np.cos(angles)

print(f"{STUDENT_NAME}'s Angles:", angles)
print("Sine:", sine_vals)
print("Cosine:", cos_vals)

Brylle Edsil F. Untalasco's Angles: [0.         0.8975979  1.7951958  2.6927937  3.5903916  4.48798951
 5.38558741 6.28318531]
Sine: [ 0.00000000e+00  7.81831482e-01  9.74927912e-01  4.33883739e-01
 -4.33883739e-01 -9.74927912e-01 -7.81831482e-01 -2.44929360e-16]
Cosine: [ 1.          0.6234898  -0.22252093 -0.90096887 -0.90096887 -0.22252093
  0.6234898   1.        ]


In [55]:
import numpy as np

STUDENT_NAME = "Brylle Edsil F. Untalasco"
STUDENT_ID = 384

np.random.seed(STUDENT_ID)

arr = np.random.randint(1, STUDENT_ID % 50 + 20, size=(4,4))

arr[::2, ::2] = 0

print(f"{STUDENT_NAME}'s Modified 4x4 Array:\n", arr)

Brylle Edsil F. Untalasco's Modified 4x4 Array:
 [[ 0 30  0 13]
 [26  5 23 36]
 [ 0 19  0 18]
 [48  8 41 17]]


In [56]:
import numpy as np

STUDENT_NAME = "Brylle Edsil F. Untalasco"
STUDENT_ID = 384

np.random.seed(STUDENT_ID)

scores = np.random.randint(0, STUDENT_ID % 100 + 50, 10)

grades = np.where(scores >= STUDENT_ID % 70, 'Pass', 'Fail')

print(f"{STUDENT_NAME}'s Scores:", scores)
print("Grades:", grades)

Brylle Edsil F. Untalasco's Scores: [93 12  4 59 81 47 40 16 55 86]
Grades: ['Pass' 'Fail' 'Fail' 'Pass' 'Pass' 'Pass' 'Pass' 'Fail' 'Pass' 'Pass']


In [57]:
import numpy as np

STUDENT_NAME = "Brylle Edsil F. Untalasco"
STUDENT_ID = 384

np.random.seed(STUDENT_ID)

arr = np.random.randint(1, STUDENT_ID % 50 + 20, size=(3,4))

flat_arr = arr.flatten()
transposed_arr = arr.T

print("Original array:\n", arr)
print("Flattened:", flat_arr)
print("Transposed:\n", transposed_arr)

Original array:
 [[39 30 36 13]
 [26  5 23 36]
 [50 19 22 18]]
Flattened: [39 30 36 13 26  5 23 36 50 19 22 18]
Transposed:
 [[39 26 50]
 [30  5 19]
 [36 23 22]
 [13 36 18]]


In [58]:
import numpy as np

STUDENT_NAME = "Brylle Edsil F. Untalasco"
STUDENT_ID = 384

np.random.seed(STUDENT_ID)

arr = np.random.randint(1, STUDENT_ID % 50 + 20, (3,3))

mask = arr % 2 == 0
arr[mask] = -1

print("Array with conditional replacements:\n", arr)

Array with conditional replacements:
 [[39 -1 -1]
 [13 -1  5]
 [23 -1 -1]]


In [59]:
import numpy as np
import pandas as pd

STUDENT_NAME = "Brylle Edsil F. Untalasco"
STUDENT_ID = 384

np.random.seed(STUDENT_ID)

df = pd.DataFrame({
    'Name': [STUDENT_NAME]*5,
    'Score': np.random.randint(50, 150, 5),
    'YearsCodePro': np.random.randint(0, STUDENT_ID % 20 + 10, 5)
})

print(df)

                        Name  Score  YearsCodePro
0  Brylle Edsil F. Untalasco    143             6
1  Brylle Edsil F. Untalasco    149             3
2  Brylle Edsil F. Untalasco     62            11
3  Brylle Edsil F. Untalasco     75             1
4  Brylle Edsil F. Untalasco     54             2


In [60]:
import numpy as np
import pandas as pd

STUDENT_NAME = "Brylle Edsil F. Untalasco"
STUDENT_ID = 384

np.random.seed(STUDENT_ID)

df = pd.DataFrame({
    'EdLevel': ['Bachelor','Master','PhD','Bachelor','Master'],
    'ConvertedComp': np.random.randint(40000, 150000, 5)
})

avg_salary = df.groupby('EdLevel')['ConvertedComp'].mean()

print(avg_salary)

EdLevel
Bachelor    103454.0
Master       83715.0
PhD         100569.0
Name: ConvertedComp, dtype: float64


In [61]:
import numpy as np
import pandas as pd

STUDENT_NAME = "Brylle Edsil F. Untalasco"
STUDENT_ID = 384

np.random.seed(STUDENT_ID)

df = pd.DataFrame({
    'Country': ['Philippines','USA','UK','Canada','Germany'],
    'ConvertedComp': np.random.randint(40000, 150000, 5)
})

top5 = df.sort_values(by='ConvertedComp', ascending=False)

print(top5)

       Country  ConvertedComp
4      Germany         121571
3       Canada         105238
0  Philippines         101670
2           UK         100569
1          USA          45859


In [ ]:
    import numpy as np
    import pandas as pd

    STUDENT_NAME = "Brylle Edsil F. Untalasco"
    STUDENT_ID = 384

    np.random.seed(STUDENT_ID)

    df = pd.DataFrame({
        'Name':[STUDENT_NAME]*5,
        'YearsCodePro': np.random.randint(0, STUDENT_ID % 20 + 10, 5)
    })

    high_exp = df[df['YearsCodePro'] > STUDENT_ID % 10]

    print(high_exp)

                        Name  YearsCodePro
0  Brylle Edsil F. Untalasco             6
1  Brylle Edsil F. Untalasco            13
3  Brylle Edsil F. Untalasco            12
4  Brylle Edsil F. Untalasco             9


In [63]:
import numpy as np
import pandas as pd

STUDENT_NAME = "Brylle Edsil F. Untalasco"
STUDENT_ID = 384

np.random.seed(STUDENT_ID)

df = pd.DataFrame({'ConvertedComp': np.random.randint(40000, 150000, 5)})

bins = [0, 50000, 100000, 150000, 200000]
labels = ['0-50k', '50-100k', '100-150k', '>150k']

df['Bracket'] = pd.cut(df['ConvertedComp'], bins=bins, labels=labels)

print(df)

   ConvertedComp   Bracket
0         101670  100-150k
1          45859     0-50k
2         100569  100-150k
3         105238  100-150k
4         121571  100-150k


In [64]:
import numpy as np
import pandas as pd

STUDENT_NAME = "Brylle Edsil F. Untalasco"
STUDENT_ID = 384

np.random.seed(STUDENT_ID)

df = pd.DataFrame({
    'ConvertedComp': np.random.randint(40000, 150000, 5)
})

df['LogComp'] = np.log(df['ConvertedComp'])

print(df)

   ConvertedComp    LogComp
0         101670  11.529488
1          45859  10.733327
2         100569  11.518599
3         105238  11.563980
4         121571  11.708254


In [65]:
import numpy as np
import pandas as pd

STUDENT_NAME = "Brylle Edsil F. Untalasco"
STUDENT_ID = 384

np.random.seed(STUDENT_ID)

df = pd.DataFrame({
    'YearsCodePro': np.random.randint(0, STUDENT_ID % 20 + 10, 5),
    'ConvertedComp': np.random.randint(40000, 150000, 5)
})

corr_matrix = df.corr()

print(corr_matrix)

               YearsCodePro  ConvertedComp
YearsCodePro       1.000000      -0.192216
ConvertedComp     -0.192216       1.000000


In [ ]:
import numpy as np
import pandas as pd

STUDENT_NAME = "Brylle Edsil F. Untalasco"
STUDENT_ID = 384

np.random.seed(STUDENT_ID)

df = pd.DataFrame({
    'EdLevel':['Bachelor','Master','PhD','Bachelor','Master'],
    'ConvertedComp': np.random.randint(40000, 150000, 5)
})

summary = df.groupby('EdLevel')['ConvertedComp'].agg(['mean','median','std']).fillna(0).reset_index()

print(summary)

    EdLevel      mean    median           std
0  Bachelor  103454.0  103454.0   2522.956995
1    Master   83715.0   83715.0  53536.468617
2       PhD  100569.0  100569.0           NaN


In [67]:
import numpy as np
import pandas as pd

STUDENT_NAME = "Brylle Edsil F. Untalasco"
STUDENT_ID = 384

np.random.seed(STUDENT_ID)

df = pd.DataFrame({'ConvertedComp': np.random.randint(40000, 150000, 5)})

threshold = 110000

df['HighPay'] = np.where(df['ConvertedComp'] > threshold, 'Yes', 'No')

print(df)

   ConvertedComp HighPay
0         101670      No
1          45859      No
2         100569      No
3         105238      No
4         121571     Yes


In [68]:
import numpy as np
import pandas as pd

STUDENT_NAME = "Brylle Edsil F. Untalasco"
STUDENT_ID = 384

np.random.seed(STUDENT_ID)

df = pd.DataFrame({
    'Country': ['Philippines','USA','UK','Canada','Germany'],
    'ConvertedComp': np.random.randint(40000, 150000, 5)
})

top_countries = df.groupby('Country')['ConvertedComp'].agg(['mean','max'])

print(top_countries)

                 mean     max
Country                      
Canada       105238.0  105238
Germany      121571.0  121571
Philippines  101670.0  101670
UK           100569.0  100569
USA           45859.0   45859
